# Generated by Django 2.0 on 2018-03-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bptjob', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bptjob',
            old_name='published_date',
            new_name='date_job_completed',
        ),
        migrations.RenameField(
            model_name='bptjob',
            old_name='created_date',
            new_name='date_job_submitted',
        ),
        migrations.RenameField(
            model_name='bptjob',
            old_name='title',
            new_name='jobid',
        ),
        migrations.RenameField(
            model_name='bptjob',
            old_name='author',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='bptjob',
            name='text',
        ),
        migrations.AddField(
            model_name='bptjob',
            name='platform',
            field=models.CharField(default='LINUXR_X86', max_length=200),
        ),
        migrations.AddField(
            model_name='bptjob',
            name='userid',
            field=models.CharField(default='USERJOE', max_length=200),
        ),
    ]
